# Generated by Django 5.1.4 on 2024-12-15 16:20

import django.db.models.deletion
import ekg_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EKG',
            fields=[
                ('id_ekg', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ekg_data', models.FileField(upload_to='ekg_files/')),
                ('status', models.IntegerField(choices=[(1, 'In queue'), (2, 'Completed')], default=1)),
                ('motive', models.TextField()),
                ('comorbidities', models.TextField()),
                ('medications', models.TextField()),
                ('symptoms', models.TextField()),
                ('observations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[ekg_app.models.validate_cpf])),
                ('birth_date', models.DateField()),
                ('risk_level', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.TextField()),
                ('p_wave', models.TextField()),
                ('pr_interval', models.TextField()),
                ('qrs_complex', models.TextField()),
                ('qt_interval', models.TextField()),
                ('conclusions', models.TextField()),
                ('ekg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekg_app.ekg')),
            ],
        ),
        migrations.AddField(
            model_name='ekg',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekg_app.patient'),
        ),
    ]
